FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# dependencies
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt update
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y zip unzip curl wget tar git
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y cmake make build-essential

# for CCES
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND dpkg --add-architecture i386
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386 libgtk2.0-0:i386 libxtst6:i386
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y gtk2-engines-murrine:i386 libcanberra-gtk-module:i386 gtk2-engines:i386

# Cleanup
RUN apt-get clean